remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: My Arduino Projects
description: These are the projects I made back in college, simulated with Tinkercad
